name: "Chromatic"

on: push

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
